import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* Hedear section  */}
        <section id='header'>
            {/* main container  */}
            <div className='container max-w-7xl p-6 mx-auto'>
                
            </div>
        </section>
        
      </main>
    </>
  )
}
